name: flutter_vant_kit
description: A vant-style flutter UI library.You can use this library to quickly build your application.

version: 0.2.7
homepage: https://github.com/benjaken/flutter_vant_kit

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  multi_image_picker: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true